[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_counter = "3LCC97iBmYU27ron9HQFEFMguNJuGUYFBuBdq8kYfbzn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/vscode/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
